### ISSUE TITLE
Another fucking error....

### ISSUE THREAD

**Issue by BrawlBox** [BrawlBox/BrawlBoxIssues#211]
I ran BrawlBox and got this error:

Failed to save settings: An error occurred loading a configuration file: There is not enough space on the disk.
 (C:\Users\admin\AppData\Local\BrawlBox\BrawlBox.exe_Url_ooe2241y14xxloxd1aetnyg5tl4iioux\0.77.6004.34063\user.config)
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
   at System.Configuration.SettingsBase.SaveCore()
   at System.Configuration.SettingsBase.Save()
   at System.Configuration.ApplicationSettingsBase.Save()
   at System.Windows.Forms.AudioPlaybackPanel.set_VolumePercent(Nullable`1 value)
   at System.Windows.Forms.AudioPlaybackPanel..ctor()
   at BrawlBox.MainForm.InitializeComponent()
   at BrawlBox.MainForm..ctor()
   at BrawlBox.MainForm.get_Instance()
   at BrawlBox.Program.Main(String[] args)

v0.77
Failed to save settings: An error occurred loading a configuration file: There is not enough space on the disk.
 (C:\Users\admin\AppData\Local\BrawlBox\BrawlBox.exe_Url_ooe2241y14xxloxd1aetnyg5tl4iioux\0.77.6004.34063\user.config)
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
   at System.Configuration.SettingsBase.SaveCore()
   at System.Configuration.SettingsBase.Save()
   at System.Configuration.ApplicationSettingsBase.Save()
   at System.Windows.Forms.AudioPlaybackPanel.set_VolumePercent(Nullable`1 value)
   at System.Windows.Forms.AudioPlaybackPanel..ctor()
   at BrawlBox.MainForm.InitializeComponent()
   at BrawlBox.MainForm..ctor()
   at BrawlBox.MainForm.get_Instance()
   at BrawlBox.Program.Main(String[] args)

**Comment by PierHGS** [comment]
The models doesn't show up once I select it or Preview it.
