### ISSUE TITLE
I can't open .brstm files.

### ISSUE THREAD

**Issue by AmeliaTransQueen** [BrawlBox/BrawlBoxIssues#215]
When I try, it gives me the error of openal32.dll
   at OpenTK.Audio.AudioContext.CreateContext(String device, Int32 freq, Int32 refresh, Boolean sync, Boolean enableEfx, MaxAuxiliarySends efxAuxiliarySends)
   at OpenTK.Audio.AudioContext..ctor()
   at System.Audio.AudioProvider.Create(AudioDevice device)
   at System.Windows.Forms.AudioPlaybackPanel.TargetChanged(IAudioSource newTarget)
   at System.Windows.Forms.AudioPlaybackPanel.set_TargetSource(IAudioSource value)
   at BrawlBox.MainForm.resourceTree_SelectionChanged(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at BrawlBox.ResourceTree.set_SelectedNode(TreeNode value)
   at BrawlBox.ResourceTree.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at BrawlBox.ResourceTree.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by The-Silver-Kid** [comment]
I had this issue too and I fixed it by installing OpenAL to my system using the installer at https://www.openal.org/downloads/

**Comment by The-Silver-Kitsune** [comment]
I fixed this issue on my system by reinstalling OpenAL from their webpage
https://www.openal.org/downloads/
