### ISSUE TITLE
System.ArgumentException

### ISSUE THREAD

**Issue by Heath123** [BrawlBox/BrawlBoxIssues#218]
Opened one file, then another. It also could't connect to the internet, so I posted it manually

Value does not fall within the expected range.
   at System.Win32.DirectSound.IDirectSound8.CreateSoundBuffer(DSBufferDesc& pcDSBufferDesc, IDirectSoundBuffer8& ppDSBuffer, IntPtr pUnkOuter)
   at System.Audio.wAudioBuffer..ctor(wAudioProvider parent, DSBufferDesc& desc)
   at System.Audio.wAudioProvider.CreateBuffer(IAudioStream target)
   at System.Windows.Forms.BrstmConverterDialog.LoadAudio(String path)
   at System.Windows.Forms.BrstmConverterDialog.LoadAudio()
   at System.Windows.Forms.BrstmConverterDialog.btnBrowse_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Hibiki0506** [comment]
I have this problem too, and it appears only with Multi-Channel WAVs, that have more than 2 Audio Channels.
![unbenannt](https://user-images.githubusercontent.com/32351488/39537772-dc0feec6-4e3a-11e8-963d-33ab31ec7531.PNG)
