### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by MDHEXT** [BrawlBox/BrawlBoxIssues#219]
Insufficient memory to continue the execution of the program.
   at System.Runtime.InteropServices.Marshal.AllocHGlobal(IntPtr cb)
   at System.Audio.PCMStream..ctor(Byte[] wavData)
   at System.Windows.Forms.BrstmConverterDialog.LoadAudio(String path)
   at System.Windows.Forms.BrstmConverterDialog.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)

**Comment by libertyernie** [comment]
Could you post a link to the file that caused this error?

**Comment by MDHEXT** [comment]
Is it possible that trying to encode audio at a high bitrate caused this???
