### ISSUE TITLE
unknown issue

### ISSUE THREAD

**Issue by MDHEXT** [BrawlBox/BrawlBoxIssues#220]
Value does not fall within the expected range.
   at System.Win32.DirectSound.IDirectSound8.CreateSoundBuffer(DSBufferDesc& pcDSBufferDesc, IDirectSoundBuffer8& ppDSBuffer, IntPtr pUnkOuter)
   at System.Audio.wAudioBuffer..ctor(wAudioProvider parent, DSBufferDesc& desc)
   at System.Audio.wAudioProvider.CreateBuffer(IAudioStream target)
   at System.Windows.Forms.BrstmConverterDialog.LoadAudio(String path)
   at System.Windows.Forms.BrstmConverterDialog.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)

**Comment by libertyernie** [comment]
That's weird. Can you post a link to the file that caused this? Or is it any audio file?

**Comment by MDHEXT** [comment]
It was a wav file encoded in a 32-bit float

**Comment by MDHEXT** [comment]
Using 16-bit audio encoding works

**Comment by MDHEXT** [comment]
I already deleted the audio files

**Comment by MDHEXT** [comment]
Can you make it so that 32 bit encoded uncompressed pcm (wav) files are supported??

**Comment by libertyernie** [comment]
I don't have a lot of time to look into this at the moment. [VGAudio](https://github.com/Thealexbarney/VGAudio) (and [LoopingAudioConverter](https://github.com/libertyernie/loopingaudioconverter)) seem to work for this, though.
