### ISSUE TITLE
another problem (might be sample rate)

### ISSUE THREAD

**Issue by MDHEXT** [BrawlBox/BrawlBoxIssues#221]
No samples could be read from the stream
   at BrawlLib.Wii.Audio.RSTMConverter.Encode(IAudioStream stream, IProgressTracker progress, WaveEncoding encoding)
   at System.Windows.Forms.BrstmConverterDialog.btnOkay_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by MDHEXT** [comment]
file is bigger than 10mb so i cant send it.

**Comment by MDHEXT** [comment]
46.8mb
