### ISSUE TITLE
pcm 16 encode error

### ISSUE THREAD

**Issue by MDHEXT** [BrawlBox/BrawlBoxIssues#223]
No samples could be read from the stream
   at BrawlLib.Wii.Audio.RSTMConverter.Encode(IAudioStream stream, IProgressTracker progress, WaveEncoding encoding)
   at System.Windows.Forms.BrstmConverterDialog.btnOkay_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by libertyernie** [comment]
What file are you encoding? Is it some kind of wav file?

**Comment by MDHEXT** [comment]
A 16-bit wav file. I was encoding the brstm as pcm.
