### ISSUE TITLE
Crash Upon Texture Import

### ISSUE THREAD

**Issue by sonich2401** [BrawlBox/BrawlBoxIssues#227]
Index was outside the bounds of the array.
   at System.BitmapExtension.GuessIfAlphaInverted(Bitmap bmp)
   at System.Windows.Forms.TextureConverterDialog.Recommend()
   at System.Windows.Forms.TextureConverterDialog.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)

Version 0.78
Does this whenever I import textures. It mostly happens with large textures but if i scale them down It doesnt crash but at the end it will say there was somthing wrong with the header.

**Comment by libertyernie** [comment]
How large are the textures (what dimensions)?
