### ISSUE TITLE
Cant preview models

### ISSUE THREAD

**Issue by BrawlBox** [BrawlBox/BrawlBoxIssues#28]
No Poligon

Model Won't Load

Model Preview Does Not Load

??????

Model won't show up
When I try to preview a model, I get the following message:

Unable to find an entry point named 'glGetUniformLocation' in DLL 'opengl32.dll'.
   at OpenTK.Graphics.OpenGL.GL.Core.GetUniformLocation(UInt32 program, String name)
   at OpenTK.Graphics.OpenGL.GL.GetUniformLocation(Int32 program, String name)
   at BrawlLib.OpenGL.GLTexture.Bind(Int32 index, Int32 program)
   at BrawlLib.SSBB.ResourceNodes.MDL0TextureNode.Load(Int32 index, Int32 program)
   at BrawlLib.SSBB.ResourceNodes.MDL0TextureNode.Prepare(MDL0MaterialRefNode mRef, Int32 shaderProgramHandle, String palette)
   at BrawlLib.SSBB.ResourceNodes.MDL0MaterialRefNode.Bind(Int32 prog)
   at BrawlLib.SSBB.ResourceNodes.MDL0ObjectNode.Render(Boolean wireframe, Boolean useShaders, MDL0MaterialNode material)
   at BrawlLib.SSBB.ResourceNodes.DrawCall.Render(ModelPanelViewport viewport)
   at System.Windows.Forms.ModelPanel.OnRenderViewport(PaintEventArgs e, GLViewport v)
   at BrawlLib.OpenGL.GLPanel.OnRender(PaintEventArgs e)
   at BrawlLib.OpenGL.GLPanel.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Model Won't Show

im on safemode and this error entry point not found

Model doesn't show up when I open it's .pac file

I can't see the models
how do you manage to see the model

can't view model
trying to open a model to preview movesets, but a red x appears instead

Model Viewing Error
As I right clicked on the model, I clicked Preview All Models. By the time it only opened the only model in there, This error shows up.

Whenever i click on a model file, Brawlbox throws an error. This has always happened since i updated Brawlbox.

v0.76b_h2
Unable to find an entry point named 'glGetUniformLocation' in DLL 'opengl32.dll'.
   at OpenTK.Graphics.OpenGL.GL.Core.GetUniformLocation(UInt32 program, String name)
   at OpenTK.Graphics.OpenGL.GL.GetUniformLocation(Int32 program, String name)
   at BrawlLib.OpenGL.GLTexture.Bind(Int32 index, Int32 program)
   at BrawlLib.SSBB.ResourceNodes.MDL0TextureNode.Load(Int32 index, Int32 program)
   at BrawlLib.SSBB.ResourceNodes.MDL0TextureNode.Prepare(MDL0MaterialRefNode mRef, Int32 shaderProgramHandle, String palette)
   at BrawlLib.SSBB.ResourceNodes.MDL0MaterialRefNode.Bind(Int32 prog)
   at BrawlLib.SSBB.ResourceNodes.MDL0ObjectNode.Render(Boolean wireframe, Boolean useShaders, MDL0MaterialNode material)
   at BrawlLib.SSBB.ResourceNodes.DrawCall.Render(ModelPanelViewport viewport)
   at System.Windows.Forms.ModelPanel.OnRenderViewport(PaintEventArgs e, GLViewport v)
   at BrawlLib.OpenGL.GLPanel.OnRender(PaintEventArgs e)
   at BrawlLib.OpenGL.GLPanel.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by lukebergen** [comment]
Any updates on this?
